Renamed the API ingestion files to reflect ecommerce focus

diff --git a/.github/workflows/ecommerce_api_ingestor.yml b/.github/workflows/ecommerce_api_ingestor.yml
--- a/.github/workflows/ecommerce_api_ingestor.yml
+++ b/.github/workflows/ecommerce_api_ingestor.yml
@@ -1,4 +1,4 @@
-name: 🧠 API Auto-Ingestion
+name: 🧠 Ecommerce API Auto-Ingestion
 
 on:
   schedule:
@@ -8,7 +8,7 @@ on:
 
 jobs:
   api-ingestion:
-    name : 🚀 Run API Ingestion job
+    name : 🚀 Run Ecommerce API Ingestion job
     runs-on: ubuntu-latest
 
     steps:
@@ -33,10 +33,10 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: 🚀 Run API Ingestion
+      - name: 🚀 Run Ecommerce API Ingestion
         run: |
           set -e
-          python level4_api_ingestion_engine/api_ingestor.py  
+          python level4_api_ingestion_engine/ecommerce_api.py  
           
        
       - name: 🕵️ Debug output
@@ -51,7 +51,7 @@ jobs:
           echo "=== Checking data folder ==="
           ls -l data/
           echo "=== Head of the CSV file ==="
-          head -n 5 data/API_dataset.csv || echo "⚠️ CSV file not found"
+          head -n 5 data/ecommerce_api_dataset.csv || echo "⚠️ CSV file not found"
           echo "=== Git diff ==="
           git diff --stat
    
@@ -59,7 +59,7 @@ jobs:
         run: |
           git config --global user.name "api-ingestion[bot]"
           git config --global user.email "api-ingestor[bot]@users.noreply.github.com"
-          git add data/API_dataset.csv
+          git add data/ecommerce_api_dataset.csv
           git commit -m "🧠 API-Data-ingestion update: $(date)" || echo "No changes to commit"
           git push https://x-access-token:${{ secrets.GT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
         env:
